#!/usr/bin/env python3
"""Small, repeatable Training I/O runner for the AI SSD Training Cases.

The runner intentionally measures storage supply behavior instead of model
accuracy.  It uses only the Python standard library so it can run on a clean
Windows test host.  Use --prepare only for a small smoke dataset; qualification
runs should point --data-dir at the prepared workload dataset from the plan.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import shutil
import statistics
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Callable, Iterable


@dataclass(frozen=True)
class CaseSpec:
    case_id: str
    model: str
    mode: str
    workers: tuple[int, ...]
    target_au: float
    chunk_bytes: int = 1024 * 1024


CASE_SPECS: dict[str, CaseSpec] = {
    "AI-TRN-001": CaseSpec("AI-TRN-001", "UNet3D/A100", "sequential", (1, 2, 4), 0.90),
    "AI-TRN-002": CaseSpec("AI-TRN-002", "UNet3D/H100", "sequential", (1, 2, 4), 0.90),
    "AI-TRN-003": CaseSpec("AI-TRN-003", "UNet3D/B200", "sequential", (1, 2, 4, 8), 0.90),
    "AI-TRN-004": CaseSpec("AI-TRN-004", "RetinaNet/B200", "small_file", (1, 4, 8, 16), 0.85),
    "AI-TRN-005": CaseSpec("AI-TRN-005", "RetinaNet/MI355", "small_file", (1, 4, 8, 16), 0.85),
    "AI-TRN-006": CaseSpec("AI-TRN-006", "CosmoFlow/A100", "shuffle", (1, 2, 4), 0.70),
    "AI-TRN-007": CaseSpec("AI-TRN-007", "CosmoFlow/H100", "shuffle", (1, 2, 4, 8), 0.70),
    "AI-TRN-008": CaseSpec("AI-TRN-008", "ResNet50/A100", "record", (1, 2, 4), 0.90),
    "AI-TRN-009": CaseSpec("AI-TRN-009", "ResNet50/H100", "record", (1, 2, 4, 8), 0.90),
    "AI-TRN-010": CaseSpec("AI-TRN-010", "DLRM/B200", "columnar", (1, 2, 4), 0.70),
    "AI-TRN-011": CaseSpec("AI-TRN-011", "DLRM/MI355", "columnar", (1, 4, 8, 16), 0.70),
    "AI-TRN-012": CaseSpec("AI-TRN-012", "Flux/B200", "sequential", (4, 8, 16), 0.90),
    "AI-TRN-013": CaseSpec("AI-TRN-013", "Flux/MI355", "burst", (4, 8, 16), 0.90),
    "AI-TRN-014": CaseSpec("AI-TRN-014", "UNet3D/RetinaNet", "saturation", (1, 2, 4, 8, 16), 0.90),
    "AI-TRN-015": CaseSpec("AI-TRN-015", "Reader scaling", "saturation", (1, 2, 4, 8, 16, 32), 0.90),
    "AI-TRN-016": CaseSpec("AI-TRN-016", "Cache/path matrix", "cache_matrix", (1, 2, 4), 0.90),
}


def discover_files(data_dir: Path) -> list[Path]:
    files = [p for p in data_dir.rglob("*") if p.is_file() and p.stat().st_size > 0]
    if not files:
        raise FileNotFoundError(f"no input files found under {data_dir}")
    return sorted(files)


def prepare_smoke_data(data_dir: Path, mode: str, sample_mib: int) -> None:
    data_dir.mkdir(parents=True, exist_ok=True)
    marker = data_dir / ".ai_ssd_training_smoke"
    if marker.exists():
        return
    if mode == "small_file":
        for index in range(256):
            path = data_dir / f"sample_{index:04d}.jpg"
            path.write_bytes(os.urandom(64 * 1024))
    else:
        block = b"A" * (1024 * 1024)
        for index in range(4):
            path = data_dir / f"sample_{index:02d}.bin"
            with path.open("wb") as handle:
                for _ in range(max(1, sample_mib)):
                    handle.write(block)
    marker.write_text("smoke dataset generated by ai_ssd_training_case_runner.py\n", encoding="utf-8")


def bounded_append(values: list[float], value: float, limit: int = 20_000) -> None:
    if len(values) < limit:
        values.append(value)
    else:
        index = random.randrange(len(values) + 1)
        if index < limit:
            values[index] = value


def run_workers(
    paths: list[Path],
    duration_sec: int,
    workers: int,
    worker: Callable[[list[Path], threading.Event, int, int], tuple[int, int, list[float]]],
    chunk_bytes: int,
    seed: int,
) -> dict[str, float | int]:
    stop = threading.Event()
    start = time.perf_counter()
    with ThreadPoolExecutor(max_workers=workers) as pool:
        futures = [pool.submit(worker, paths, stop, chunk_bytes, seed + i) for i in range(workers)]
        time.sleep(duration_sec)
        stop.set()
        results = [future.result() for future in futures]
    elapsed = max(time.perf_counter() - start, 0.001)
    total_bytes = sum(result[0] for result in results)
    operations = sum(result[1] for result in results)
    latencies = [latency for result in results for latency in result[2]]
    latencies.sort()
    p99 = latencies[min(len(latencies) - 1, int(len(latencies) * 0.99))] if latencies else 0.0
    return {
        "workers": workers,
        "elapsed_sec": round(elapsed, 3),
        "bytes": total_bytes,
        "operations": operations,
        "throughput_mib_s": round(total_bytes / elapsed / 1024 / 1024, 3),
        "iops": round(operations / elapsed, 3),
        "p99_ms": round(p99, 3),
    }


def worker_sequential(paths: list[Path], stop: threading.Event, chunk_bytes: int, seed: int) -> tuple[int, int, list[float]]:
    del seed
    total = operations = 0
    latencies: list[float] = []
    while not stop.is_set():
        for path in paths:
            if stop.is_set():
                break
            with path.open("rb", buffering=0) as handle:
                while not stop.is_set():
                    started = time.perf_counter()
                    block = handle.read(chunk_bytes)
                    elapsed_ms = (time.perf_counter() - started) * 1000
                    if not block:
                        break
                    total += len(block)
                    operations += 1
                    bounded_append(latencies, elapsed_ms)
    return total, operations, latencies


def worker_small_file(paths: list[Path], stop: threading.Event, chunk_bytes: int, seed: int) -> tuple[int, int, list[float]]:
    del chunk_bytes
    rng = random.Random(seed)
    total = operations = 0
    latencies: list[float] = []
    while not stop.is_set():
        path = paths[rng.randrange(len(paths))]
        started = time.perf_counter()
        path.stat()
        with path.open("rb", buffering=0) as handle:
            block = handle.read(4096)
        latencies.append((time.perf_counter() - started) * 1000)
        total += len(block)
        operations += 1
    return total, operations, latencies


def worker_shuffle(paths: list[Path], stop: threading.Event, chunk_bytes: int, seed: int) -> tuple[int, int, list[float]]:
    rng = random.Random(seed)
    total = operations = 0
    latencies: list[float] = []
    while not stop.is_set():
        path = paths[rng.randrange(len(paths))]
        size = path.stat().st_size
        offset = 0 if size <= chunk_bytes else rng.randrange(0, size - chunk_bytes, chunk_bytes)
        started = time.perf_counter()
        with path.open("rb", buffering=0) as handle:
            handle.seek(offset)
            block = handle.read(chunk_bytes)
        latencies.append((time.perf_counter() - started) * 1000)
        total += len(block)
        operations += 1
    return total, operations, latencies


def worker_record(paths: list[Path], stop: threading.Event, chunk_bytes: int, seed: int) -> tuple[int, int, list[float]]:
    # TFRecord-like fixed-size sample reads: physical pattern is the important part here.
    return worker_shuffle(paths, stop, max(chunk_bytes, 2 * 1024 * 1024), seed)


def worker_columnar(paths: list[Path], stop: threading.Event, chunk_bytes: int, seed: int) -> tuple[int, int, list[float]]:
    # Parquet-like row-group/column reads: alternate aligned chunks instead of reading the whole file.
    return worker_shuffle(paths, stop, max(chunk_bytes // 2, 512 * 1024), seed)


def worker_burst(paths: list[Path], stop: threading.Event, chunk_bytes: int, seed: int) -> tuple[int, int, list[float]]:
    rng = random.Random(seed)
    total = operations = 0
    latencies: list[float] = []

    def read_one() -> tuple[int, int, float]:
        path = paths[rng.randrange(len(paths))]
        size = path.stat().st_size
        offset = 0 if size <= chunk_bytes else rng.randrange(0, size - chunk_bytes, chunk_bytes)
        started = time.perf_counter()
        with path.open("rb", buffering=0) as handle:
            handle.seek(offset)
            block = handle.read(chunk_bytes)
        return len(block), 1, (time.perf_counter() - started) * 1000

    while not stop.is_set():
        for _ in range(8):
            if stop.is_set():
                break
            total_one, ops_one, latency_one = read_one()
            total += total_one
            operations += ops_one
            latencies.append(latency_one)
        stop.wait(0.25)
    return total, operations, latencies


def run_one_mode(spec: CaseSpec, paths: list[Path], duration_sec: int, workers: int, seed: int, mode: str | None = None) -> dict[str, float | int | str]:
    selected = mode or spec.mode
    workers = max(1, workers)
    worker_map = {
        "sequential": worker_sequential,
        "small_file": worker_small_file,
        "shuffle": worker_shuffle,
        "record": worker_record,
        "columnar": worker_columnar,
        "burst": worker_burst,
    }
    if selected not in worker_map:
        raise ValueError(f"unsupported access mode: {selected}")
    result = run_workers(paths, duration_sec, workers, worker_map[selected], spec.chunk_bytes, seed)
    result["mode"] = selected
    return result


def run_case(spec: CaseSpec, paths: list[Path], duration_sec: int, repeat: int, seed: int) -> list[dict[str, object]]:
    results: list[dict[str, object]] = []
    if spec.mode == "saturation":
        sweep_duration = max(5, duration_sec // 3)
        for workers in spec.workers:
            results.append(run_one_mode(spec, paths, sweep_duration, workers, seed + workers, "sequential"))
        return results
    if spec.mode == "cache_matrix":
        # These are deliberately named controls.  Confirm the actual physical read bytes with Windows monitoring.
        for mode in ("sequential", "shuffle", "small_file"):
            for trial in range(repeat):
                results.append(run_one_mode(spec, paths, duration_sec, spec.workers[0], seed + trial, mode))
        return results
    # Sweep every worker point from the case profile, then repeat each point.
    # This keeps the executable behavior aligned with the worker values listed
    # in the case table (for example 1/4/8/16 for the small-file case).
    for workers in spec.workers:
        for trial in range(repeat):
            results.append(run_one_mode(spec, paths, duration_sec, workers, seed + workers * 100 + trial))
    return results


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="AI SSD Training Case runner")
    parser.add_argument("--case", choices=sorted(CASE_SPECS), required=True)
    parser.add_argument("--data-dir", type=Path, required=True)
    parser.add_argument("--result-dir", type=Path, required=True)
    parser.add_argument("--duration-sec", type=int, default=60, help="duration of each trial")
    parser.add_argument("--repeat", type=int, default=3)
    parser.add_argument("--workers", type=int, default=0, help="0 uses the case profile")
    parser.add_argument("--seed", type=int, default=20260806)
    parser.add_argument("--prepare", action="store_true", help="create a small smoke dataset")
    parser.add_argument("--sample-mib", type=int, default=16)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    spec = CASE_SPECS[args.case]
    if args.prepare:
        prepare_smoke_data(args.data_dir, spec.mode, args.sample_mib)
    paths = discover_files(args.data_dir)
    duration_sec = max(5, args.duration_sec)
    repeat = max(1, args.repeat)
    results = run_case(spec, paths, duration_sec, repeat, args.seed)
    args.result_dir.mkdir(parents=True, exist_ok=True)
    output = {
        "case_id": spec.case_id,
        "model": spec.model,
        "mode": spec.mode,
        "input_files": len(paths),
        "target_au": spec.target_au,
        "duration_sec_per_trial": duration_sec,
        "repeat": repeat,
        "results": results,
        "note": "AU/任务指标需由对应训练 workload 记录；本脚本负责供数、吞吐、IOPS、P99 和实际读写证据。",
    }
    output_path = args.result_dir / f"{spec.case_id}.json"
    output_path.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(output, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
