"""Shared execution support for the generated AI SSD case scripts.

Each ``test_*.py`` file contains its own case metadata and delegates the
repeatable mechanics here.  Without ``--execute`` a script writes a plan
manifest only.  ``--execute`` runs a scaled, standard-library smoke probe;
the full MLPerf/DLIO/Milvus workload can be substituted by the lab command
recorded in the manifest.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import shutil
import statistics
import subprocess
import sys
import threading
import time
from array import array
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _parse_args(spec: dict[str, Any]) -> argparse.Namespace:
    default_result = Path(os.environ.get("AI_SSD_RESULTS", "results")) / spec["case_id"]
    parser = argparse.ArgumentParser(description=f"AI SSD {spec['case_id']} {spec['case_name']}")
    parser.add_argument("--data-dir", type=Path, default=Path(os.environ.get("DUT_DATA", "data")))
    parser.add_argument("--result-dir", type=Path, default=default_result)
    parser.add_argument("--duration-sec", type=int, default=30)
    parser.add_argument("--repeat", type=int, default=1)
    parser.add_argument("--sample-mib", type=int, default=16)
    parser.add_argument("--sample-points", type=int, default=1000)
    parser.add_argument("--execute", action="store_true", help="run a scaled smoke probe")
    parser.add_argument("--prepare", action="store_true", help="create a small local probe dataset")
    parser.add_argument("--full-scale", action="store_true", help="disable the checkpoint shard safety cap; use only on an authorized DUT")
    parser.add_argument("--seed", type=int, default=20260806)
    return parser.parse_args()


def _files(data_dir: Path) -> list[Path]:
    return sorted(p for p in data_dir.rglob("*") if p.is_file() and p.stat().st_size > 0)


def _prepare_files(data_dir: Path, count: int = 32, size: int = 64 * 1024) -> None:
    data_dir.mkdir(parents=True, exist_ok=True)
    marker = data_dir / ".ai_ssd_case_probe"
    if marker.exists():
        return
    payload = bytes((index % 251 for index in range(size)))
    for index in range(count):
        (data_dir / f"probe_{index:04d}.bin").write_bytes(payload)
    marker.write_text("generated by ai_ssd_test_cases\n", encoding="utf-8")


def _write_json(result_dir: Path, name: str, value: dict[str, Any]) -> Path:
    result_dir.mkdir(parents=True, exist_ok=True)
    path = result_dir / name
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def _measure_reads(paths: list[Path], duration_sec: int, workers: int, seed: int) -> dict[str, Any]:
    if not paths:
        raise FileNotFoundError("no non-empty input files found")
    stop = threading.Event()
    totals = [0] * workers
    ops = [0] * workers
    latencies: list[float] = []
    lock = threading.Lock()

    def worker(slot: int) -> None:
        rng = random.Random(seed + slot)
        while not stop.is_set():
            path = paths[rng.randrange(len(paths))]
            started = time.perf_counter()
            with path.open("rb", buffering=0) as handle:
                block = handle.read(1024 * 1024)
            elapsed = (time.perf_counter() - started) * 1000
            totals[slot] += len(block)
            ops[slot] += 1
            with lock:
                latencies.append(elapsed)

    started = time.perf_counter()
    with ThreadPoolExecutor(max_workers=workers) as pool:
        futures = [pool.submit(worker, slot) for slot in range(workers)]
        time.sleep(max(1, duration_sec))
        stop.set()
        for future in futures:
            future.result()
    elapsed = max(time.perf_counter() - started, 0.001)
    latencies.sort()
    p99 = latencies[min(len(latencies) - 1, int(len(latencies) * 0.99))] if latencies else 0.0
    total_bytes = sum(totals)
    total_ops = sum(ops)
    return {
        "workers": workers,
        "elapsed_sec": round(elapsed, 3),
        "bytes": total_bytes,
        "operations": total_ops,
        "throughput_mib_s": round(total_bytes / elapsed / 1024 / 1024, 3),
        "iops": round(total_ops / elapsed, 3),
        "p99_ms": round(p99, 3),
    }


def _run_base(spec: dict[str, Any], args: argparse.Namespace) -> dict[str, Any]:
    data_dir = args.data_dir.resolve()
    result_dir = args.result_dir.resolve()
    usage_path = data_dir if data_dir.exists() else (result_dir.parent if result_dir.parent.exists() else _repo_root())
    usage = shutil.disk_usage(usage_path)
    files = _files(data_dir) if data_dir.exists() else []
    result: dict[str, Any] = {
        "mode": "base_probe",
        "data_dir": str(data_dir),
        "result_dir": str(result_dir),
        "file_count": len(files),
        "data_bytes": sum(p.stat().st_size for p in files),
        "disk_free_bytes": usage.free,
        "note": "路径和容量类 Case 不自动填充生产盘；填充率变化需在授权目录执行。",
    }
    if spec["case_id"] == "AI-BASE-003" and files:
        repeats = []
        for _ in range(max(1, args.repeat)):
            repeats.append(_measure_reads(files, args.duration_sec, 1, args.seed))
        values = [float(item["throughput_mib_s"]) for item in repeats]
        mean = statistics.mean(values) if values else 0.0
        result["repeats"] = repeats
        result["throughput_cv"] = round(statistics.pstdev(values) / mean if mean else 0.0, 4)
    return result


def _run_training(spec: dict[str, Any], args: argparse.Namespace) -> dict[str, Any]:
    command = [
        sys.executable,
        str(_repo_root() / "tools" / "ai_ssd_training_case_runner.py"),
        "--case",
        spec["case_id"],
        "--data-dir",
        str(args.data_dir),
        "--result-dir",
        str(args.result_dir),
        "--duration-sec",
        str(args.duration_sec),
        "--repeat",
        str(max(1, args.repeat)),
    ]
    if args.prepare:
        command.append("--prepare")
    if args.sample_mib:
        command.extend(["--sample-mib", str(args.sample_mib)])
    completed = subprocess.run(command, cwd=_repo_root(), check=False)
    return {"mode": "training_io_runner", "command": command, "returncode": completed.returncode}


def _run_checkpoint(spec: dict[str, Any], args: argparse.Namespace) -> dict[str, Any]:
    args.result_dir.mkdir(parents=True, exist_ok=True)
    requested_shards = int(spec.get("shards", 8))
    shard_count = requested_shards if args.full_scale else min(requested_shards, 8)
    size = max(1, args.sample_mib) * 1024 * 1024
    payload = bytes((index % 251 for index in range(min(size, 4 * 1024 * 1024))) )
    paths: list[Path] = []
    write_started = time.perf_counter()
    for shard in range(shard_count):
        path = args.result_dir / f"checkpoint_shard_{shard:04d}.bin"
        with path.open("wb", buffering=0) as handle:
            remaining = size
            while remaining:
                block = payload[: min(remaining, len(payload))]
                handle.write(block)
                remaining -= len(block)
            handle.flush()
            os.fsync(handle.fileno())
        paths.append(path)
    write_elapsed = max(time.perf_counter() - write_started, 0.001)
    digest = hashlib.sha256()
    read_started = time.perf_counter()
    read_bytes = 0
    for path in paths:
        with path.open("rb", buffering=0) as handle:
            while block := handle.read(1024 * 1024):
                digest.update(block)
                read_bytes += len(block)
    read_elapsed = max(time.perf_counter() - read_started, 0.001)
    return {
        "mode": "checkpoint_fsync_read_probe",
        "requested_shards": requested_shards,
        "scaled_shards": shard_count,
        "scaled_bytes_per_shard": size,
        "write_elapsed_sec": round(write_elapsed, 3),
        "read_elapsed_sec": round(read_elapsed, 3),
        "read_bytes": read_bytes,
        "sha256": digest.hexdigest(),
        "note": "默认使用 sample-mib 缩放；真实 TB 级 Case 需替换为正式 checkpoint workload，并另行完成 cold cache 门禁。",
    }


def _run_kv(spec: dict[str, Any], args: argparse.Namespace) -> dict[str, Any]:
    args.result_dir.mkdir(parents=True, exist_ok=True)
    rng = random.Random(args.seed)
    slots = max(4, min(int(spec.get("users", 32)), 256))
    slot_size = max(4096, args.sample_mib * 1024)
    payload = bytes(rng.randrange(256) for _ in range(slot_size))
    slot_paths = []
    for index in range(slots):
        path = args.result_dir / f"kv_slot_{index:04d}.bin"
        path.write_bytes(payload)
        slot_paths.append(path)
    latencies: list[float] = []
    read_bytes = write_bytes = 0
    deadline = time.perf_counter() + max(1, args.duration_sec)
    while time.perf_counter() < deadline:
        path = slot_paths[rng.randrange(len(slot_paths))]
        started = time.perf_counter()
        if rng.random() < 0.2:
            path.write_bytes(payload)
            write_bytes += len(payload)
        else:
            read_bytes += len(path.read_bytes())
        latencies.append((time.perf_counter() - started) * 1000)
    latencies.sort()
    p99 = latencies[min(len(latencies) - 1, int(len(latencies) * 0.99))] if latencies else 0.0
    return {
        "mode": "kv_slot_tier_probe",
        "slots": slots,
        "read_bytes": read_bytes,
        "write_bytes": write_bytes,
        "operations": len(latencies),
        "p99_ms": round(p99, 3),
        "note": "该脚本验证 NVMe tier 的读写、尾延迟和容量趋势；MLPerf KV Cache SLA 需接入对应 workload。",
    }


def _run_vdb(spec: dict[str, Any], args: argparse.Namespace) -> dict[str, Any]:
    rng = random.Random(args.seed)
    points = max(16, min(args.sample_points, 5000))
    dimensions = int(spec.get("dimensions", 128))
    vectors = [[rng.random() for _ in range(dimensions)] for _ in range(points)]
    query = list(vectors[0])
    started = time.perf_counter()
    best_index = -1
    best_distance = float("inf")
    for index, vector in enumerate(vectors):
        distance = sum((left - right) ** 2 for left, right in zip(query, vector))
        if distance < best_distance:
            best_distance = distance
            best_index = index
    elapsed = max(time.perf_counter() - started, 0.000001)
    return {
        "mode": "vector_search_probe",
        "sample_points": points,
        "dimensions": dimensions,
        "best_index": best_index,
        "recall_at_1": 1.0 if best_index == 0 else 0.0,
        "qps": round(1 / elapsed, 3),
        "p99_ms": round(elapsed * 1000, 3),
        "note": "该脚本为可重复的向量查询 smoke probe；正式 Recall/QPS 结果需使用固定 Milvus/index workload。",
    }


def _run_mixed(spec: dict[str, Any], args: argparse.Namespace) -> dict[str, Any]:
    _prepare_files(args.data_dir)
    paths = _files(args.data_dir)
    stop = threading.Event()
    foreground = {"bytes": 0, "ops": 0, "latencies": []}
    background = {"bytes": 0, "ops": 0}

    def foreground_worker() -> None:
        rng = random.Random(args.seed)
        while not stop.is_set():
            path = paths[rng.randrange(len(paths))]
            started = time.perf_counter()
            foreground["bytes"] += len(path.read_bytes())
            foreground["ops"] += 1
            foreground["latencies"].append((time.perf_counter() - started) * 1000)

    def background_worker() -> None:
        payload = b"B" * 64 * 1024
        index = 0
        while not stop.is_set():
            path = args.result_dir / f"background_{index % 8}.bin"
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open("ab") as handle:
                handle.write(payload)
                handle.flush()
                os.fsync(handle.fileno())
            background["bytes"] += len(payload)
            background["ops"] += 1
            index += 1

    started = time.perf_counter()
    with ThreadPoolExecutor(max_workers=2) as pool:
        first = pool.submit(foreground_worker)
        second = pool.submit(background_worker)
        time.sleep(max(1, args.duration_sec))
        stop.set()
        first.result()
        second.result()
    elapsed = max(time.perf_counter() - started, 0.001)
    latencies = sorted(foreground["latencies"])
    p99 = latencies[min(len(latencies) - 1, int(len(latencies) * 0.99))] if latencies else 0.0
    return {
        "mode": "foreground_background_probe",
        "elapsed_sec": round(elapsed, 3),
        "foreground_bytes": foreground["bytes"],
        "foreground_ops": foreground["ops"],
        "foreground_p99_ms": round(p99, 3),
        "background_bytes": background["bytes"],
        "background_ops": background["ops"],
        "note": "混合 Case 以可重复的前台读/后台写 probe 校验干扰趋势；正式 AU、KV SLA 或 Recall 需接入对应 workload。",
    }


def execute_case(spec: dict[str, Any]) -> int:
    args = _parse_args(spec)
    args.result_dir.mkdir(parents=True, exist_ok=True)
    manifest: dict[str, Any] = {
        "case_id": spec["case_id"],
        "category": spec["category"],
        "case_name": spec["case_name"],
        "purpose": spec["purpose"],
        "steps": spec["steps"],
        "test_duration": spec["test_duration"],
        "command": spec["command"],
        "standard": spec["standard"],
        "data_dir": str(args.data_dir.resolve()),
        "result_dir": str(args.result_dir.resolve()),
        "execute": args.execute,
        "status": "PLANNED",
    }
    if not args.execute:
        path = _write_json(args.result_dir, f"{spec['case_id']}_plan.json", manifest)
        print(json.dumps({"status": "PLANNED", "case_id": spec["case_id"], "manifest": str(path)}, ensure_ascii=False, indent=2))
        return 0

    if args.prepare and spec["category"] not in {"checkpoint", "kv", "vdb"}:
        _prepare_files(args.data_dir)
    category = spec["category"]
    if category == "training":
        result = _run_training(spec, args)
    elif category == "base":
        result = _run_base(spec, args)
    elif category == "checkpoint":
        result = _run_checkpoint(spec, args)
    elif category == "kv":
        result = _run_kv(spec, args)
    elif category == "vdb":
        result = _run_vdb(spec, args)
    elif category == "mixed":
        result = _run_mixed(spec, args)
    else:
        raise ValueError(f"unsupported category: {category}")
    manifest.update({"status": "EXECUTED", "result": result})
    path = _write_json(args.result_dir, f"{spec['case_id']}_result.json", manifest)
    print(json.dumps({"status": "EXECUTED", "case_id": spec["case_id"], "manifest": str(path), "result": result}, ensure_ascii=False, indent=2))
    return int(result.get("returncode", 0)) if isinstance(result, dict) else 0
